//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public long Id { get; set; }
        public string ShopId { get; set; }
        public string CustName { get; set; }
        public string CustCell { get; set; }
        public string CustEmgName { get; set; }
        public string CustEmgCell { get; set; }
        public string CustLevel { get; set; }
        public string Loyalty { get; set; }
        public string CustAddress { get; set; }
        public string Gender { get; set; }
        public string Note { get; set; }
        public string VetName { get; set; }
        public string VetTel { get; set; }
        public string DiscountType { get; set; }
        public int InShopCount { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
