//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpInfo
    {
        public long Id { get; set; }
        public string ShopId { get; set; }
        public string EmpId { get; set; }
        public string CName { get; set; }
        public string PersonalId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public string WorkRole { get; set; }
        public string WorkLevel { get; set; }
        public string EmpStatus { get; set; }
        public string EmpCell { get; set; }
        public string EmpAddress { get; set; }
        public string EmergencyCell { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<decimal> HourlySalary { get; set; }
        public Nullable<decimal> AuunalOffRemain { get; set; }
        public System.DateTime StartWorkDate { get; set; }
        public Nullable<System.DateTime> EndWorkDate { get; set; }
        public string Note { get; set; }
    }
}
