//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalary
    {
        public long Id { get; set; }
        public System.DateTime PayYM { get; set; }
        public string EmpId { get; set; }
        public Nullable<decimal> Bouns { get; set; }
        public Nullable<decimal> PersonalOff { get; set; }
        public Nullable<decimal> SickOff { get; set; }
        public Nullable<decimal> AnnualOff { get; set; }
        public Nullable<decimal> OtherExpense { get; set; }
        public string Note { get; set; }
        public decimal TotalSalary { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
