//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroomerMatchMaking
    {
        public long Id { get; set; }
        public string MatchId { get; set; }
        public string GroomerCell { get; set; }
        public string ShopId { get; set; }
        public System.DateTime MatchSDT { get; set; }
        public System.DateTime MatchEDT { get; set; }
    }
}
