//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroomerInfo
    {
        public long Id { get; set; }
        public string PersonalId { get; set; }
        public string Name { get; set; }
        public string GroomerCell { get; set; }
        public string GroomerStatus { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> BasicSalary { get; set; }
        public Nullable<int> HourlySalary { get; set; }
        public string ServiceArea1 { get; set; }
        public string ServiceArea2 { get; set; }
        public string ServiceArea3 { get; set; }
        public string ServiceArea4 { get; set; }
        public string ServiceArea5 { get; set; }
        public string SkillLevel { get; set; }
        public string Skill1 { get; set; }
        public string Skill2 { get; set; }
        public string Skill3 { get; set; }
        public string Skill4 { get; set; }
        public string Skill5 { get; set; }
        public string Introduce { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
