//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroomerReputation
    {
        public long Id { get; set; }
        public string MatchId { get; set; }
        public string GroomerServiceLevel { get; set; }
        public string GroomerReputation1 { get; set; }
        public string NoteFromGroomer { get; set; }
        public string ShopServiceLevel { get; set; }
        public string ShopReputation { get; set; }
        public string NoteFromShop { get; set; }
    }
}
