//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HannahEntities : DbContext
    {
        public HannahEntities()
            : base("name=HannahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyOwner> CompanyOwner { get; set; }
        public virtual DbSet<CompanyShop> CompanyShop { get; set; }
        public virtual DbSet<EmpInfo> EmpInfo { get; set; }
        public virtual DbSet<EmpSalary> EmpSalary { get; set; }
        public virtual DbSet<EmpWorkSchedule> EmpWorkSchedule { get; set; }
        public virtual DbSet<GroomerInfo> GroomerInfo { get; set; }
        public virtual DbSet<GroomerMatchMaking> GroomerMatchMaking { get; set; }
        public virtual DbSet<GroomerReputation> GroomerReputation { get; set; }
        public virtual DbSet<ItemInfo> ItemInfo { get; set; }
        public virtual DbSet<LoginInfo> LoginInfo { get; set; }
        public virtual DbSet<PetBreed> PetBreed { get; set; }
        public virtual DbSet<PetCategory> PetCategory { get; set; }
        public virtual DbSet<PetInfo> PetInfo { get; set; }
        public virtual DbSet<ProductForSell> ProductForSell { get; set; }
        public virtual DbSet<PurchaseDetails> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoice { get; set; }
        public virtual DbSet<ShopCapacity> ShopCapacity { get; set; }
        public virtual DbSet<ShopCustomerInfo> ShopCustomerInfo { get; set; }
        public virtual DbSet<ShopReservation> ShopReservation { get; set; }
        public virtual DbSet<ShopServiceDef> ShopServiceDef { get; set; }
        public virtual DbSet<ShopServicePackage> ShopServicePackage { get; set; }
        public virtual DbSet<SysBasicService> SysBasicService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SysFunctionPrivilege> SysFunctionPrivilege { get; set; }
        public virtual DbSet<SysKeyTypeValue> SysKeyTypeValue { get; set; }
        public virtual DbSet<SysMaxIds> SysMaxIds { get; set; }
        public virtual DbSet<SysModule> SysModule { get; set; }
        public virtual DbSet<SysPrivilege> SysPrivilege { get; set; }
        public virtual DbSet<VendorInfo> VendorInfo { get; set; }
    }
}
