//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoginInfo
    {
        [DisplayName("Account Number")]
        [Required]
        public string AccountId { get; set; }

        [DisplayName("Account Name")]
        public string AccountName { get; set; }

        public string AccountType { get; set; }
        public string AccountStatus { get; set; }

        [DisplayName("Password")]
        [Required]
        public string Password { get; set; }

        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginFailedCount { get; set; }
        public string LoginIPAddress { get; set; }
        public string CustomerTimeZone { get; set; }
    }
}
