//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    //using System.ComponentModel.DataAnnotations;
    
    public partial class PetCategory
    {
        //[Display(Name ="類型編號")]
        public long Id { get; set; }
        //[Display(Name = "類型英文名")]
        public string Category { get; set; }
        //[Display(Name = "類型中文名")]
        public string CName { get; set; }
        //[Display(Name = "建立時間")]
        public System.DateTime CreateDateTime { get; set; }
    }
}
