//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductForSell
    {
        public long Id { get; set; }
        public string VendorId { get; set; }
        public string ItemSN { get; set; }
        public string ShopId { get; set; }
        public decimal ItemCost { get; set; }
        public Nullable<decimal> ItemSellPrice { get; set; }
        public Nullable<decimal> ItemSpecialSell { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public System.DateTime ItemInDate { get; set; }
        public Nullable<System.DateTime> ItemSellDate { get; set; }
    }
}
