//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public string InvoiceId { get; set; }
        public int ListNum { get; set; }
        public string PurchaseType { get; set; }
        public string ServiceId { get; set; }
        public string ServiceDiscountType { get; set; }
        public Nullable<decimal> ServiceDiscountRate { get; set; }
        public Nullable<int> ServiceCharge { get; set; }
        public string ItemSN { get; set; }
        public string ItemDiscountType { get; set; }
        public Nullable<decimal> ItemDiscountRate { get; set; }
        public Nullable<int> ItemChage { get; set; }
    }
}
