//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopServicePackage
    {
        public long Id { get; set; }
        public string BusinessId { get; set; }
        public string ShopId { get; set; }
        public string PackageId { get; set; }
        public string PackageType { get; set; }
        public string ServiceId1 { get; set; }
        public string ServiceId2 { get; set; }
        public string ServiceId3 { get; set; }
        public string ServiceId4 { get; set; }
        public string ServiceId5 { get; set; }
        public string ServiceId6 { get; set; }
        public string ServiceId7 { get; set; }
        public string ServiceId8 { get; set; }
        public string ServiceId9 { get; set; }
        public string ServiceId10 { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> ServiceCount { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
