//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFunctionPrivilege
    {
        public long Id { get; set; }
        public string ModuleId { get; set; }
        public string FunctionId { get; set; }
        public string FunctionName { get; set; }
        public string AdminFlag { get; set; }
        public string BusinessOwnerFlag { get; set; }
        public string ShopOwnerFlag { get; set; }
        public string EmployeeFlag { get; set; }
        public string CustomerFlag { get; set; }
        public string VendorFlag { get; set; }
        public string DesignerFlag { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
